export const internalPaths = {
	main: '/',
	faq: '/faq',
	letsConnect: '/lets-connect',
	login: '/login',
	authorize: '/authorize',
	forgotPassword: '/forgot-password',
	aboutUs: '/about-us',
	banking: '/banking',
	cookiesPolicy: '/cookies-policy',
	riskAppetite: '/risk-appetite',
	termsOfService: '/terms-of-service',
	comingSoon: '/multi-cards',
	findOutMore: '/find-out-more',
	otc: '/otc',
	yield: '/yield',
};
