export const internalPaths = {
	main: '/',
	faq: '/faq',
	letsConnect: '/lets-connect',
	login: '/login',
	authorize: '/authorize',
	forgotPassword: '/forgot-password',
	aboutUs: '/about-us',
	banking: '/banking',
	cookiesPolicy: '/cookies-policy',
	riskAppetite: '/risk-appetite',
	privacyPolicy: '/privacy-policy',
	termsOfService: '/terms-of-service',
	comingSoon: '/multi-cards',
};
