name: Build and Push Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        service:
          - name: frontend
            context: ./frontend

          - name: dashboard
            context: ./dashboard

          - name: email-service
            context: ./email-service

          - name: admin
            context: ./admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.service.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: Dockerfile
          build_args: |
            VITE_STRAPI_API_URL=https://api.${{ secrets.DOMAIN }}
            VITE_DASHBOARD_URL=https://dashboard.${{ secrets.DOMAIN }}
            VITE_EMAIL_SERVICE_URL=https://email.${{ secrets.DOMAIN }}
            VITE_CONTACT_EMAIL=${{ secrets.EMAIL }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ steps.meta.outputs.REPO_NAME }}/${{ matrix.service.name }}:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ steps.meta.outputs.REPO_NAME }}/${{ matrix.service.name }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=local,src=/tmp/.buildx-cache